# Generated by Django 4.0.2 on 2022-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookCRUD', '0003_alter_bookinfo_qty_alter_student_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
