# Generated by Django 4.0.2 on 2022-02-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookCRUD', '0004_alter_bookinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
