# Generated by Django 4.0.2 on 2022-02-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookCRUD', '0005_alter_bookinfo_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
