# Generated by Django 4.0.2 on 2022-03-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookCRUD', '0006_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='user',
        ),
    ]
